
blank_issues_enabled: false
contact_links:
  - name: Passkeys Developer Discussions
    url: https://passkeys.dev/discuss
    about: A discussion forum for developer-related questions around implementing passkeys
  - name: FIDO2 Deployment or Implementation Question
    url: https://groups.google.com/a/fidoalliance.org/g/fido-dev
    about: Please use the FIDO-DEV list/group to ask questions about FIDO2 deployment and implementations
  - name: Report a bug in Google Chrome
    url: https://bugs.chromium.org/p/chromium/issues/wizard
    about: Report a WebAuthn-related bug in Google Chrome (Chromium)
  - name: Report a bug in Mozilla Firefox
    url: https://bugzilla.mozilla.org/home
    about: Report a WebAuthn-related bug in Mozilla Firefox (Gecko)
  - name: Report a bug in Apple Safari
    url: https://webkit.org/reporting-bugs/
    about: Report a WebAuthn-related bug in Apple's Safari (WebKit)
