Vagrant.configure("2") do |config|
  # Use Ubuntu 16.04 Xenial as a base box.
  config.vm.box = "ubuntu/xenial64"

  # Install bikeshed
  config.vm.provision "shell", path: "provision.sh"

  # Mount project directory at /vagrant
  config.vm.synced_folder '../..', '/vagrant'
end
