name: Check test vectors
on:
  pull_request:
  push:

jobs:
  check-test-vectors:
    name: Ensure test vectors are up to date
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check if test vectors are up to date
        run: |
          pip install poetry
          cd test-vectors
          ./inject-generated-content.sh --check
